Bugfix for loading correct resolvers files in production build
vuestorefront/storefront-api pull request #104
Opened 2021-01-05 08:28 UTC by cewald

### Related issues

closes #100

### Short description and why it's useful

Prevents exception during start in production mode.

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/storefront-api/blob/develop/CONTRIBUTING.md)

2021-02-03 17:02 UTC, Fifciu requested changes

2021-02-03 17:02 UTC, Fifciu commented on packages/lib/helpers/graphql.ts
> +  const fileLoaderExt = process.env.VS_ENV && process.env.VS_ENV === 'dev' ? 'ts' : 'js'
Let's just simplify it to the:
```ts
const fileLoaderExt = process.env.VS_ENV === 'dev' ? 'ts' : 'js'
```

2021-02-03 17:39 UTC, cewald commented on packages/lib/helpers/graphql.ts
> +  const fileLoaderExt = process.env.VS_ENV && process.env.VS_ENV === 'dev' ? 'ts' : 'js'
Done :)

2021-02-04 09:28 UTC, Fifciu approved these changes
Great job thanks

2021-02-04 09:31 UTC, merged